import Head from "next/head";

// Components
import Homepage from "@/component/page/home/homepage.component";

// Data
import { fetchTeam } from "@/data/sub-teams";

export default function Home(props) {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Homepage team={props.fetchedTeam.team} />
    </>
  );
}

export function getStaticProps() {
  const fetchedTeam = fetchTeam();

  return {
    props: {
      fetchedTeam,
    },
    revalidate: 1800,
  };
}
